version: '2'

services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      - MONGODB_ROOT_PASSWORD=password123

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8017:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: mecy
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: password123
  vops:
    image: mecy:5000/dockermgeo/vedops:latest
    ports:
      - "27080:3200"
    environment:
      - LOG_LEVEL=debug
      - MONGODB_HOST=mecy
